batch: 32
cache: true
data: car-damage-detector-1/data.yaml
deterministic: true
device: mps
epochs: 50
exist_ok: true
imgsz: 416
name: roboflow-continuous
optimizer: auto
patience: 15
plots: true
pretrained: true
project: detection-model/runs
resume: false
save: true
seed: 0
val: true
verbose: true
